Repository Leets-Official/Fling-FE, pull requests merged in 2024-02, with the labels that each got.

#121 [feat] - 편지작성 로직변경
  src/apis/hooks/usePostNickname.ts
  src/apis/service/nickname.ts
  src/apis/service/writeLetter.ts
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/WritePage/components/ChooseCard/index.tsx
  src/pages/WritePage/components/ChooseFlower/index.tsx
  src/pages/WritePage/index.tsx
  src/types/index.ts
Labels: 은지

#119 [feat] - 전체 반응형 UI 및 링크 복사 기능
  src/components/Sidebar/index.tsx
  src/index.css
  src/pages/DecorateBouquetPage/index.tsx
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/FlowerFrame/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/components/ReceivedLetter/index.tsx
  src/pages/MyPage/components/SentLetter/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/SignUpPage/index.tsx
  tailwind.config.js
Labels: 주하

#120 [feat] - 에러 및 로딩페이지 구현
  package-lock.json
  package.json
  src/pages/CollectionPage/index.tsx
  src/pages/Error404Page/index.tsx
  src/pages/Error500Page/index.tsx
  src/pages/LoadingPage/index.tsx
  src/pages/OauthPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
Labels: 승준

#129 [refactor] - 라우팅 간 로딩 처리
  src/App.tsx
Labels: 승준

#125 [feat] - 메인페이지 편지 확인
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/FlowerFrame/index.tsx
  src/pages/MainPage/components/Letter/index.tsx
  src/pages/MainPage/components/UncreatedBouquet/index.tsx
  src/pages/MainPage/components/index.ts
  src/pages/MainPage/index.tsx
  src/types/index.ts
  src/utils/getLeftDays.ts
Labels: 주하

#132 [style] - 로그인 화면 UI 수정
  src/assets/images/login/login_1.png
  src/assets/images/login/login_2.png
  src/assets/images/login/login_3.png
  src/assets/images/login/login_4.png
  src/components/MerryGoRound/index.tsx
  src/pages/LoginPage/index.tsx
Labels: 승준

#133 [style] - 도감페이지 UI 수정
  src/pages/CollectionPage/components/Content/index.tsx
Labels: 승준

#130 [feat] - 에러페이지, 로딩페이지 적용
  src/apis/hooks/useGetFlower.ts
  src/apis/hooks/useGetStore.ts
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/components/Mailbox/index.tsx
  src/pages/MyPage/components/ReceivedLetter/index.tsx
  src/pages/MyPage/components/SentLetter/index.tsx
  src/pages/StorePage/index.tsx
Labels: 은지

#135 [refactor] - 편지작성 타입변경 및 가운데정렬
  public/vite.svg
  src/apis/hooks/usePostStoreCard.ts
  src/apis/hooks/usePostStoreDeco.ts
  src/apis/hooks/usePostStoreFlower.ts
  src/assets/images/items/gray.png
  src/components/Item/index.tsx
  src/components/Sidebar/Box/index.tsx
  src/pages/LoadingPage/index.tsx
  src/pages/MainPage/components/Letter/index.tsx
  src/pages/StorePage/components/PurchasePage/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
  src/pages/StorePage/index.tsx
  src/pages/WritePage/components/ChooseCard/index.tsx
Labels: 은지

#136 [feat] - 랜덤코인페이지 마크업 및 기능
  src/apis/hooks/index.ts
  src/apis/hooks/usePostCoin.ts
  src/assets/check.png
  src/assets/images/butterfly.png
  src/assets/images/card.png
  src/assets/images/coinBackground.png
  src/assets/images/giftBox/giftBox.png
  src/assets/images/giftBox/giftBoxBottom.png
  src/assets/images/giftBox/giftBoxTop.png
  src/index.css
  src/pages/CoinDrawPage/components/GiftBox/index.tsx
  src/pages/CoinDrawPage/components/Header/index.tsx
  src/pages/CoinDrawPage/components/index.ts
  src/pages/CoinDrawPage/index.tsx
  src/pages/DecorateBouquetPage/components/ItemFrame/index.tsx
  src/pages/DecorateBouquetPage/components/TabContents/index.tsx
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/index.tsx
  tailwind.config.js
Labels: 주하

#138 [refactor] - 각종 버그 수정
  src/apis/apiClient.ts
  src/pages/CollectionPage/index.tsx
  src/pages/OauthPage/index.tsx
Labels: 승준

#141 [refactor] - 회원가입 및 로그인 피드백 반영
  src/pages/CreateBouquetPage/components/Name/index.tsx
  src/pages/OauthPage/index.tsx
  src/pages/SignUpPage/index.tsx
Labels: 승준

#143 [refactor] - 생성페이지 리본 위치 수정
  src/pages/CreateBouquetPage/components/Ribbon/index.tsx
Labels: 승준

#146 [refactor] - 메인페이지 유저피드백
  index.html
  src/assets/images/flower_card.png
  src/assets/images/flower_card.svg
  src/assets/images/index.ts
  src/assets/images/ribbons/index.ts
  src/assets/images/ribbons/ribbon1.png
  src/assets/images/ribbons/ribbon1.svg
  src/assets/images/ribbons/ribbon2.png
  src/assets/images/ribbons/ribbon2.svg
  src/assets/images/ribbons/ribbon3.png
  src/assets/images/ribbons/ribbon3.svg
  src/assets/images/wrapper.jpeg
  src/components/Button/index.tsx
  src/pages/DecorateBouquetPage/components/BouquetFrame/index.tsx
  src/pages/DecorateBouquetPage/components/Ribbons/index.tsx
  src/pages/DecorateBouquetPage/components/TabContents/index.tsx
  src/pages/DecorateBouquetPage/index.tsx
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/FlowerFrame/index.tsx
  src/pages/MainPage/components/FlowerStrokes/가느다란_안개_속_오솔길.tsx
  src/pages/MainPage/components/FlowerStrokes/달콤한_소원.tsx
  src/pages/MainPage/components/FlowerStrokes/반짝이는_달빛_호수.tsx
  src/pages/MainPage/components/FlowerStrokes/반짝이는_하늘별.tsx
  src/pages/MainPage/components/FlowerStrokes/봄날의_첫사랑.tsx
  src/pages/MainPage/components/FlowerStrokes/부드러운_사랑의_온기.tsx
  src/pages/MainPage/components/FlowerStrokes/빛나는_새로운_시작.tsx
  src/pages/MainPage/components/FlowerStrokes/산새소리에_깃든_선율.tsx
  src/pages/MainPage/components/FlowerStrokes/새싹처럼_피어난_산하늘.tsx
  src/pages/MainPage/components/FlowerStrokes/신비로운_미래의_이슬.tsx
  src/pages/MainPage/components/FlowerStrokes/신비로운_새벽_하늘.tsx
  src/pages/MainPage/components/FlowerStrokes/우아한_나비의_향연.tsx
  src/pages/MainPage/components/FlowerStrokes/은은한_오로라.tsx
  src/pages/MainPage/components/FlowerStrokes/차분한_노랫소리.tsx
  src/pages/MainPage/components/FlowerStrokes/청량한_한여름밤의_꿈.tsx
  src/pages/MainPage/components/FlowerStrokes/초승달처럼_빛나는_미소.tsx
  src/pages/MainPage/components/FlowerStrokes/평온_속_고요한_숲.tsx
  src/pages/MainPage/components/FlowerStrokes/햇살_가득한_향기.tsx
  src/pages/MainPage/components/FlowerStrokes/화려한_푸른_달빛.tsx
  src/pages/MainPage/components/FlowerStrokes/화양연화.tsx
  src/pages/MainPage/components/Ribbons/index.tsx
  src/pages/MainPage/components/UncreatedBouquet/index.tsx
  src/pages/MainPage/index.tsx
Labels: 주하

#148 [refactor] - 랜덤코인 페이지 유저피드백 모두 반영
  src/pages/CoinDrawPage/index.tsx
  tailwind.config.js
Labels: 주하

#145 [refactor] - 피드백 수정
  public/vite.svg
  src/apis/service/flower.ts
  src/apis/service/items.ts
  src/apis/service/letterReceived.ts
  src/apis/service/letterSent.ts
  src/apis/service/nickname.ts
  src/apis/service/store.ts
  src/assets/images/items/너울-카드.png
  src/assets/images/items/들꽃-카드.png
  src/assets/images/items/산속-카드.png
  src/assets/images/items/양감-카드.png
  src/assets/images/items/영문-카드.png
  src/assets/images/items/향기-카드.png
  src/components/Sidebar/Box/index.tsx
  src/components/Sidebar/Content/index.tsx
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/components/Mailbox/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
  src/pages/StorePage/index.tsx
  src/pages/WritePage/components/WriteLetter/index.tsx
Labels: 은지

#151 [refactor] - 편지닫기아이콘 디자인
  src/pages/MainPage/components/Letter/index.tsx
Labels: 주하

#152 [refactor] - 피드백 수정
  src/pages/CreateBouquetPage/components/Name/index.tsx
  src/pages/CreateBouquetPage/components/Ribbon/index.tsx
  src/pages/SignUpPage/index.tsx
Labels: 승준

#154 [refactor] - 배포전 피드백
  src/pages/CoinDrawPage/index.tsx
  src/pages/CollectionPage/index.tsx
  src/pages/StorePage/index.tsx
Labels: 은지

#155 [refactor] - 피드백 수정
  src/pages/CreateBouquetPage/components/DDay/components/Select/index.tsx
  src/pages/CreateBouquetPage/components/Ribbon/index.tsx
  src/pages/OauthPage/index.tsx
Labels: 승준

#157 Feat/#156/메인페이지 수정 및 favicon
  index.html
  public/fling.svg
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/FlowerFrame/index.tsx
Labels: 주하

#159 [feat] - 스켈레톤 UI 구현
  src/components/Item/index.tsx
  src/pages/MainPage/components/FlowerFrame/index.tsx
  src/pages/MainPage/components/ItemFrame/index.tsx
  src/pages/MyPage/components/ReceivedLetter/index.tsx
  src/pages/MyPage/components/SentLetter/index.tsx
Labels: 주하
