Repository Leets-Official/Fling-FE, pull requests merged in 2024-01, with the labels that each got.

#3 [feat] - router구현
  package-lock.json
  package.json
  src/App.tsx
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/index.ts
  src/routes/router.tsx
Labels: 주하

#5 [feat] - Button 컴포넌트 기능 구현
  src/components/Button/index.tsx
  src/components/index.ts
Labels: 주하

#8 [feat] - Dropdown 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Dropdown/Item/index.tsx
  src/components/Dropdown/Menu/index.tsx
  src/components/Dropdown/Toggle/index.tsx
  src/components/Dropdown/index.tsx
  src/components/index.ts
  tailwind.config.js
Labels: 주하

#11 [feat] - Modal 컴포넌트 기능 구현
  src/components/Modal/Content/index.tsx
  src/components/Modal/Toggle/index.tsx
  src/components/Modal/index.tsx
  src/components/index.ts
Labels: 주하

#14 [feat] - react query 세팅
  package-lock.json
  package.json
  src/App.tsx
  src/apis/apiClient.ts
Labels: 주하

#24 [feat] layout 변경 및 폰트 설정
  index.html
  src/components/Sidebar/Box/index.tsx
  src/components/Sidebar/index.tsx
  src/index.css
  src/pages/MainPage/index.tsx
  tailwind.config.js
Labels: 은지

#9 [feat] - 카카오 로그인 인가코드 받아오기
  package-lock.json
  package.json
  src/assets/fling.png
  src/assets/kakao_login_medium_wide.png
  src/components/MerryGoRound/index.tsx
  src/components/index.ts
  src/pages/LoginPage/index.tsx
  src/pages/OauthPage/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/types/index.d.ts
  tailwind.config.js
Labels: 승준

#23 [feat] - 랜덤 코인 페이지 기능 구현
  package-lock.json
  package.json
  src/assets/Icons/coin.svg
  src/assets/Icons/home.svg
  src/assets/Icons/index.ts
  src/assets/images/wrapper.jpeg
  src/assets/react.svg
  src/components/Button/index.tsx
  src/pages/CoinDrawPage/components/GiftBox/index.tsx
  src/pages/CoinDrawPage/components/Header/index.tsx
  src/pages/CoinDrawPage/components/index.ts
  src/pages/CoinDrawPage/index.tsx
  src/pages/index.ts
  src/routes/Layout.tsx
  src/routes/constants.ts
  src/routes/router.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: 주하

#28 [feat] - 상점 및 도감 아이템 컴포넌트 구현
  src/assets/images/1.png
  src/assets/images/fling.png
  src/assets/images/kakao_login_medium_wide.png
  src/components/Item/index.tsx
  src/components/index.ts
  src/pages/LoginPage/index.tsx
Labels: 승준

#31 [feat] - 폰트 설정
  src/index.css
Labels: 승준

#26 [feat] - header 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/Icons/flower.svg
  src/assets/Icons/index.ts
  src/assets/Icons/sidebar.svg
  src/components/Header/index.tsx
  src/components/Sidebar/Box/index.tsx
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/components/Mailbox/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
Labels: 은지

#33 [feat] - 아이콘 추가
  src/assets/Icons/close.svg
  src/assets/Icons/draw.svg
  src/assets/Icons/go_back.svg
  src/assets/Icons/index.ts
  src/assets/Icons/left_arrow.svg
  src/assets/Icons/right_arrow.svg
  src/assets/Icons/sidebar.svg
Labels: 주하

#42 [refactor] - Modal 컴포넌트 수정
  package-lock.json
  package.json
  src/assets/Icons/close.svg
  src/assets/Icons/draw.svg
  src/assets/Icons/go_back.svg
  src/assets/Icons/home.svg
  src/assets/Icons/left_arrow.svg
  src/assets/Icons/right_arrow.svg
  src/assets/Icons/sidebar.svg
  src/components/Modal/Content/index.tsx
  src/components/Modal/Contents/index.tsx
  src/components/Modal/Toggle/index.tsx
  src/components/Modal/index.tsx
  tailwind.config.js
Labels: 주하

#44 [refactor] - Header 컴포넌트 수정
  src/components/Header/index.tsx
  src/components/Sidebar/Box/index.tsx
  src/components/Sidebar/Content/index.tsx
  src/components/Sidebar/index.tsx
  src/components/index.ts
  src/constants/index.ts
  src/index.css
  src/pages/MainPage/index.tsx
Labels: 주하

#36 [feat] - store 초기 UI
  src/components/Header/index.tsx
  src/components/Modal/Contents/index.tsx
  src/index.css
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/StorePage/components/PurchasePage/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
  src/pages/StorePage/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
Labels: 은지

#41 [feat] - 도감페이지 구현
  src/assets/images/butterfly.png
  src/components/Button/index.tsx
  src/pages/CollectionPage/components/Content/index.tsx
  src/pages/CollectionPage/components/index.ts
  src/pages/CollectionPage/index.tsx
  src/pages/ItemPage/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
Labels: 승준

#47 [chore] - recoil 초기세팅
  package-lock.json
  package.json
  src/App.tsx
  src/recoil/index.ts
Labels: 은지

#37 [feat] - 닉네임 설정 페이지 구현
  src/assets/Icons/check.svg
  src/assets/Icons/index.ts
  src/assets/check.png
  src/components/Header/index.tsx
  src/constants/index.ts
  src/pages/NicknamePage/index.tsx
  src/pages/OauthPage/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
Labels: 승준

#51 [feat] - 구매 수량 제한 및 버튼 비활성화
  src/pages/StorePage/components/StoreItem/index.tsx
Labels: 은지

#49 [feat] - 편지작성 페이지
  package.json
  src/assets/images/0.png
  src/assets/images/2.png
  src/assets/images/3.png
  src/assets/images/4.png
  src/assets/images/card.png
  src/components/Header/index.tsx
  src/components/Item/index.tsx
  src/index.css
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/StorePage/components/PurchasePage/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
  src/pages/StorePage/index.tsx
  src/pages/WritePage/components/ChooseCard/index.tsx
  src/pages/WritePage/components/ChooseFlower/index.tsx
  src/pages/WritePage/components/WriteLetter/index.tsx
  src/pages/WritePage/components/index.ts
  src/pages/WritePage/index.tsx
  src/pages/index.ts
  src/recoil/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  tailwind.config.js
Labels: 은지

#53 [feat] - 편지함 편지내용 UI
  src/components/Header/index.tsx
  src/constants/index.ts
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/components/Mailbox/index.tsx
  src/pages/MyPage/components/ReceivedLetter/index.tsx
  src/pages/MyPage/components/SentLetter/index.tsx
  src/pages/MyPage/index.tsx
Labels: 은지

#55 [feat] - 메인페이지 구현
  index.html
  src/assets/Icons/index.ts
  src/assets/Icons/plus.svg
  src/assets/images/flowers/flower1.png
  src/assets/images/flowers/flower12.png
  src/assets/images/flowers/flower2.png
  src/assets/images/flowers/flower3.png
  src/assets/images/flowers/flower4.png
  src/assets/images/flowers/flower5.png
  src/assets/images/flowers/flower6.png
  src/assets/images/flowers/flower7.png
  src/assets/images/flowers/flower8.png
  src/assets/images/flowers/index.ts
  src/assets/images/index.ts
  src/assets/images/wrapping/back_wrapping.png
  src/assets/images/wrapping/left_wrapping.png
  src/assets/images/wrapping/right_wrapping.png
  src/components/Header/index.tsx
  src/components/Sidebar/index.tsx
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/FlowerFrame/index.tsx
  src/pages/MainPage/components/MarryGoRound/index.tsx
  src/pages/MainPage/components/UncreatedBouquet/index.tsx
  src/pages/MainPage/components/index.ts
  src/pages/MainPage/index.tsx
  src/routes/Layout.tsx
  src/utils/getLeftDays.ts
  src/utils/index.ts
Labels: 주하

#57 [feat] - 메인페이지 API 구현
  src/apis/apiClient.ts
  src/apis/hooks/index.ts
  src/apis/hooks/useGetBouquet.ts
  src/index.d.ts
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/UncreatedBouquet/index.tsx
  src/pages/MainPage/index.tsx
  src/types/index.ts
Labels: 주하

#60 [feat] - 보낸편지함 api 연결 초기 세팅
  src/apis/hooks/index.ts
  src/apis/hooks/useGetFlower.ts
  src/apis/hooks/useGetLetterSent.ts
  src/apis/service/flower.ts
  src/apis/service/index.ts
  src/apis/service/letterSent.ts
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/components/Mailbox/index.tsx
  src/pages/MyPage/components/SentLetter/index.tsx
  src/types/index.ts
Labels: 은지

#48 [feat] - 로그인페이지 UI 수정
  .gitignore
  src/apis/apiClient.ts
  src/apis/hooks/index.ts
  src/apis/hooks/usePostLogin.ts
  src/apis/hooks/usePostRegister.ts
  src/assets/Icons/index.ts
  src/assets/Icons/kakao.svg
  src/components/MerryGoRound/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/NicknamePage/index.tsx
  src/pages/OauthPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/types/index.ts
Labels: 승준

#72 [refactor] - 로그인 데이터 형식 변경
  src/pages/OauthPage/index.tsx
  src/types/index.ts
Labels: 승준

#68 [style] - 메인페이지 마크업 수정
  index.html
  src/assets/images/flower_blur.png
  src/assets/images/flower_card.png
  src/assets/images/flowers/flower1.png
  src/assets/images/flowers/flower10.png
  src/assets/images/flowers/flower11.png
  src/assets/images/flowers/flower12.png
  src/assets/images/flowers/flower13.png
  src/assets/images/flowers/flower14.png
  src/assets/images/flowers/flower15.png
  src/assets/images/flowers/flower16.png
  src/assets/images/flowers/flower17.png
  src/assets/images/flowers/flower18.png
  src/assets/images/flowers/flower19.png
  src/assets/images/flowers/flower2.png
  src/assets/images/flowers/flower20.png
  src/assets/images/flowers/flower3.png
  src/assets/images/flowers/flower4.png
  src/assets/images/flowers/flower5.png
  src/assets/images/flowers/flower6.png
  src/assets/images/flowers/flower7.png
  src/assets/images/flowers/flower8.png
  src/assets/images/flowers/flower9.png
  src/assets/images/index.ts
  src/assets/images/ribbons/ribbon1.png
  src/assets/images/ribbons/ribbon2.png
  src/assets/images/ribbons/ribbon3.png
  src/assets/images/wrapping/back_wrapping.png
  src/assets/images/wrapping/index.ts
  src/assets/images/wrapping/left_wrapping.png
  src/assets/images/wrapping/right_wrapping.png
  src/assets/images/wrapping/wrapper_back.svg
  src/assets/images/wrapping/wrapper_front_left.svg
  src/assets/images/wrapping/wrapper_front_right.svg
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/FlowerFrame/index.tsx
  src/pages/MainPage/components/MarryGoRound/index.tsx
  src/pages/MainPage/components/Ribbons/index.tsx
  src/pages/MainPage/components/UncreatedBouquet/index.tsx
  src/pages/MainPage/components/index.ts
  src/pages/MainPage/index.tsx
  tailwind.config.js
Labels: 주하

#75 [feat] - 꽃다발 디자인 수정 API 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useEditBouquet.ts
Labels: 주하

#62 [feat] - 꽃다발 생성페이지
  src/apis/hooks/index.ts
  src/apis/hooks/useGetUserInfo.ts
  src/apis/hooks/usePostBouquet.ts
  src/assets/images/create_bouquet/color/black.png
  src/assets/images/create_bouquet/color/white.png
  src/assets/images/create_bouquet/ribbon/ribbon1.png
  src/assets/images/create_bouquet/ribbon/ribbon1_wrapper.png
  src/assets/images/create_bouquet/ribbon/ribbon2.png
  src/assets/images/create_bouquet/ribbon/ribbon2_wrapper.png
  src/assets/images/create_bouquet/ribbon/ribbon3.png
  src/assets/images/create_bouquet/ribbon/ribbon3_wrapper.png
  src/assets/images/create_bouquet/wrapper/black_wrapper.png
  src/assets/images/create_bouquet/wrapper/white_wrapper.png
  src/components/Dropdown/Menu/index.tsx
  src/pages/CreateBouquetPage/components/DDay/components/Select/index.tsx
  src/pages/CreateBouquetPage/components/DDay/index.tsx
  src/pages/CreateBouquetPage/components/Name/index.tsx
  src/pages/CreateBouquetPage/components/Ribbon/index.tsx
  src/pages/CreateBouquetPage/components/Wrapper/index.tsx
  src/pages/CreateBouquetPage/components/index.ts
  src/pages/CreateBouquetPage/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/types/index.ts
Labels: 승준

#67 [refactor] - mypage api 에러 수정
  src/apis/hooks/index.ts
  src/apis/hooks/useGetFlower.ts
  src/apis/hooks/useGetLetterReceived.ts
  src/apis/service/flower.ts
  src/apis/service/index.ts
  src/apis/service/letterReceived.ts
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/components/Mailbox/index.tsx
  src/pages/MyPage/components/ReceivedLetter/index.tsx
  src/pages/MyPage/components/SentLetter/index.tsx
  src/pages/OauthPage/index.tsx
  src/types/index.ts
Labels: 은지

#64 [feat] - store api 연결
  src/apis/hooks/index.ts
  src/apis/hooks/useGetStore.ts
  src/apis/hooks/usePostStoreCard.ts
  src/apis/hooks/usePostStoreDeco.ts
  src/apis/hooks/usePostStoreFlower.ts
  src/apis/service/index.ts
  src/apis/service/store.ts
  src/apis/service/storeCard.ts
  src/apis/service/storeDeco.ts
  src/apis/service/storeFlower.ts
  src/assets/images/wrapping/wrapper_front.svg
  src/pages/StorePage/components/StoreItem/index.tsx
  src/pages/StorePage/index.tsx
  src/types/index.ts
Labels: 은지

#66 [feat] - 편지작성 api 연결
  src/apis/hooks/usePostWriteLetter.ts
  src/apis/service/index.ts
  src/apis/service/writeLetter.ts
  src/pages/WritePage/components/ChooseCard/index.tsx
  src/pages/WritePage/components/ChooseFlower/index.tsx
  src/pages/WritePage/index.tsx
  src/types/index.ts
Labels: 은지

#83 [feat] - item 일러스트 추가
  src/assets/images/0.png
  src/assets/images/1.png
  src/assets/images/2.png
  src/assets/images/3.png
  src/assets/images/4.png
  src/assets/images/items/가느다란-안개-속-오솔길.png
  src/assets/images/items/기억의-풀꽃.png
  src/assets/images/items/꽃-나비-무리.png
  src/assets/images/items/너울-카드.png
  src/assets/images/items/달-조각.png
  src/assets/images/items/달콤한-소원.png
  src/assets/images/items/동글동글-풀꽃.png
  src/assets/images/items/들꽃-카드.png
  src/assets/images/items/반짝이는-달빛-호수.png
  src/assets/images/items/반짝이는-하늘별.png
  src/assets/images/items/벚-나비-장식.png
  src/assets/images/items/봄날의-첫사랑.png
  src/assets/images/items/부드러운-사랑의-온기.png
  src/assets/images/items/부슬부슬-풀꽃.png
  src/assets/images/items/분홍-나비-장식.png
  src/assets/images/items/붉은점-나비-무리.png
  src/assets/images/items/빛나는-새로운-시작.png
  src/assets/images/items/빛나는-풀꽃.png
  src/assets/images/items/산새소리에-깃든-선율.png
  src/assets/images/items/산속-카드.png
  src/assets/images/items/새-조각.png
  src/assets/images/items/새싹처럼-피어난-산하늘.png
  src/assets/images/items/신비로운-미래의-이슬.png
  src/assets/images/items/신비로운-새벽-하늘.png
  src/assets/images/items/안아줘요-풀꽃.png
  src/assets/images/items/양감-카드.png
  src/assets/images/items/영문-카드.png
  src/assets/images/items/우아한-나비의-향연.png
  src/assets/images/items/은은한-오로라.png
  src/assets/images/items/차분한-노랫소리.png
  src/assets/images/items/청량한-한여름밤의-꿈.png
  src/assets/images/items/초승달처럼-빛나는-미소.png
  src/assets/images/items/평온-속-고요한-숲.png
  src/assets/images/items/폼폼-풀꽃.png
  src/assets/images/items/푸른-나비-무리.png
  src/assets/images/items/하양-나비-장식.png
  src/assets/images/items/하트-보석.png
  src/assets/images/items/햇살-가득한-향기.png
  src/assets/images/items/향기-카드.png
  src/assets/images/items/화려한-푸른-달빛.png
  src/assets/images/items/화양연화.png
  src/components/Item/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
Labels: 은지

#76 [feat] - 도감페이지 api 연결
  src/apis/hooks/useGetItems.ts
  src/apis/service/index.ts
  src/apis/service/items.ts
  src/pages/CollectionPage/components/Content/index.tsx
  src/pages/CollectionPage/index.tsx
  src/pages/CreateBouquetPage/index.tsx
  src/types/index.ts
Labels: 승준

#78 [refactor] - item 컴포넌트 수정
  src/components/Item/index.tsx
Labels: 승준

#82 [feat] - 메인페이지 추가 기능
  src/apis/hooks/index.ts
  src/apis/hooks/useGetBouquet.ts
  src/apis/hooks/useGetUser.ts
  src/apis/hooks/usePostBouquet.ts
  src/pages/CreateBouquetPage/index.tsx
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/Ribbons/index.tsx
  src/pages/MainPage/components/UncreatedBouquet/index.tsx
  src/pages/MainPage/index.tsx
Labels: 주하

#88 [style] - 상점페이지 마크업
  src/apis/hooks/usePostStoreCard.ts
  src/apis/hooks/usePostStoreDeco.ts
  src/apis/hooks/usePostStoreFlower.ts
  src/assets/images/bigItems/가느다란-안개-속-오솔길.png
  src/assets/images/bigItems/달콤한-소원.png
  src/assets/images/bigItems/반짝이는-달빛-호수.png
  src/assets/images/bigItems/반짝이는-하늘별.png
  src/assets/images/bigItems/봄날의-첫사랑.png
  src/assets/images/bigItems/부드러운-사랑의-온기.png
  src/assets/images/bigItems/빛나는-새로운-시작.png
  src/assets/images/bigItems/산새소리에-깃든-선율.png
  src/assets/images/bigItems/새싹처럼-피어난-산하늘.png
  src/assets/images/bigItems/신비로운-미래의-이슬.png
  src/assets/images/bigItems/신비로운-새벽-하늘.png
  src/assets/images/bigItems/우아한-나비의-향연.png
  src/assets/images/bigItems/은은한-오로라.png
  src/assets/images/bigItems/차분한-노랫소리.png
  src/assets/images/bigItems/청량한-한여름밤의-꿈.png
  src/assets/images/bigItems/초승달처럼-빛나는-미소.png
  src/assets/images/bigItems/평온-속-고요한-숲.png
  src/assets/images/bigItems/햇살-가득한-향기.png
  src/assets/images/bigItems/화려한-푸른-달빛.png
  src/assets/images/bigItems/화양연화.png
  src/assets/images/flowers/index.ts
  src/components/ConfirmPurchase.tsx
  src/components/Purchase/index.tsx
  src/pages/StorePage/components/PurchasePage/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
Labels: 은지

#85 [feat] - user api 연결
  src/pages/MyPage/components/Mailbox/Letter/index.tsx
  src/pages/MyPage/components/Mailbox/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
  src/pages/StorePage/index.tsx
  src/routes/router.tsx
Labels: 은지

#90 [feat] - 편지작성 페이지 아이템 가져오기
  src/assets/images/bigItems/너울-카드.png
  src/assets/images/bigItems/들꽃-카드.png
  src/assets/images/bigItems/산속-카드.png
  src/assets/images/bigItems/양감-카드.png
  src/assets/images/bigItems/영문-카드.png
  src/components/Item/index.tsx
  src/components/Purchase/index.tsx
  src/pages/StorePage/components/PurchasePage/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
  src/pages/WritePage/components/ChooseCard/index.tsx
  src/pages/WritePage/components/ChooseFlower/index.tsx
  src/pages/WritePage/index.tsx
Labels: 은지

#79 [refactor] - 회원가입 시 바로 메인페이지 이동
  src/apis/hooks/usePostRegister.ts
  src/pages/SignUpPage/index.tsx
Labels: 승준

#95 [style] - deco items 이미지
  src/assets/images/bigItems/기억의-풀꽃.png
  src/assets/images/bigItems/꽃-나비-무리.png
  src/assets/images/bigItems/달-조각.png
  src/assets/images/bigItems/동글동글-풀꽃.png
  src/assets/images/bigItems/벚-나비-장식.png
  src/assets/images/bigItems/부슬부슬-풀꽃.png
  src/assets/images/bigItems/분홍-나비-장식.png
  src/assets/images/bigItems/붉은점-나비-무리.png
  src/assets/images/bigItems/빛나는-풀꽃.png
  src/assets/images/bigItems/새-조각.png
  src/assets/images/bigItems/안아줘요-풀꽃.png
  src/assets/images/bigItems/폼폼-풀꽃.png
  src/assets/images/bigItems/푸른-나비-무리.png
  src/assets/images/bigItems/하양-나비-장식.png
  src/assets/images/bigItems/하트-보석.png
  src/pages/MyPage/components/ReceivedLetter/index.tsx
  src/pages/MyPage/components/SentLetter/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
Labels: 은지

#98 [feat] - 꽃다발 꾸미기 페이지 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useGetItems.ts
  src/apis/service/items.ts
  src/assets/images/ribbons/ribbonItem1.png
  src/assets/images/ribbons/ribbonItem2.png
  src/assets/images/ribbons/ribbonItem3.png
  src/assets/images/wrapping/index.ts
  src/assets/images/wrapping/wrapper_black_back.svg
  src/assets/images/wrapping/wrapper_black_front_left.svg
  src/assets/images/wrapping/wrapper_black_front_right.svg
  src/assets/images/wrapping/wrapper_black_item.svg
  src/assets/images/wrapping/wrapper_front.svg
  src/assets/images/wrapping/wrapper_front_left.svg
  src/assets/images/wrapping/wrapper_white_back.svg
  src/assets/images/wrapping/wrapper_white_front_left.svg
  src/assets/images/wrapping/wrapper_white_front_right.svg
  src/assets/images/wrapping/wrapper_white_item.svg
  src/components/Header/index.tsx
  src/pages/CollectionPage/index.tsx
  src/pages/DecorateBouquetPage/components/BouquetFrame/index.tsx
  src/pages/DecorateBouquetPage/components/FlowerFrame/index.tsx
  src/pages/DecorateBouquetPage/components/ItemFrame/index.tsx
  src/pages/DecorateBouquetPage/components/Ribbons/index.tsx
  src/pages/DecorateBouquetPage/components/TabContents/index.tsx
  src/pages/DecorateBouquetPage/components/index.ts
  src/pages/DecorateBouquetPage/index.tsx
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/FlowerFrame/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/WritePage/components/ChooseCard/index.tsx
  src/pages/WritePage/components/ChooseFlower/index.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/types/index.ts
  tailwind.config.js
  vite.config.ts
Labels: 주하

#99 [refactor] - 로그인 관련 이슈 해결
  src/apis/hooks/usePostLogin.ts
  src/pages/OauthPage/index.tsx
Labels: 승준

#93 [style] - 도감페이지 마크업
  src/apis/hooks/index.ts
  src/apis/hooks/useGetCardItemInfo.ts
  src/apis/hooks/useGetDecoItemInfo.ts
  src/apis/hooks/useGetFlowerItemInfo.ts
  src/pages/CollectionPage/components/Content/index.tsx
  src/pages/ItemPage/index.tsx
  src/routes/constants.ts
  src/types/index.ts
Labels: 승준

#100 [style] - 꽃다발 생성페이지 마크업
  src/pages/CreateBouquetPage/components/DDay/index.tsx
  src/pages/CreateBouquetPage/components/Name/index.tsx
  src/pages/CreateBouquetPage/components/Ribbon/index.tsx
  src/pages/CreateBouquetPage/components/Wrapper/index.tsx
Labels: 승준

#110 [refactor] - 로그인 이슈 해결
  src/pages/LoginPage/index.tsx
  src/pages/OauthPage/index.tsx
Labels: 승준

#113 [style] - 전체UI 수정
  index.html
  src/apis/hooks/usePostWriteLetter.ts
  src/apis/service/writeLetter.ts
  src/assets/images/bigItems/너울-카드.png
  src/assets/images/bigItems/들꽃-카드.png
  src/assets/images/bigItems/산속-카드.png
  src/assets/images/bigItems/양감-카드.png
  src/assets/images/bigItems/영문-카드.png
  src/assets/images/bigItems/향기-카드.png
  src/components/Item/index.tsx
  src/components/Sidebar/Box/index.tsx
  src/pages/MyPage/components/Mailbox/index.tsx
  src/pages/MyPage/components/SentLetter/index.tsx
  src/pages/StorePage/components/StoreItem/index.tsx
  src/pages/StorePage/index.tsx
  src/pages/WritePage/components/ChooseCard/index.tsx
  src/pages/WritePage/components/ChooseFlower/index.tsx
  src/pages/WritePage/index.tsx
Labels: 은지

#115 [feat] - 메인페이지 리다이렉트 분기 처리
  package-lock.json
  package.json
  src/apis/hooks/useGetBouquet.ts
  src/components/Sidebar/index.tsx
  src/pages/MainPage/components/CreatedBouquet/index.tsx
  src/pages/MainPage/components/FlowerFrame/index.tsx
  src/pages/MainPage/components/MarryGoRound/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/OauthPage/index.tsx
  src/recoil/index.ts
  tailwind.config.js
Labels: 주하
